<?php
/**
 * Brain Mesh Installer
 *
 * MySQL Setup for CM-1 Micronaut System
 *
 * @law ASX = XCFE = XJSON = KUHUL = AST = CM-1
 * @version 2.0.0
 */

// Prevent re-installation if already configured
$configFile = __DIR__ . '/config.php';
$lockFile = __DIR__ . '/.installed';

if (file_exists($lockFile) && !isset($_GET['force'])) {
    header("Content-Type: application/json");
    echo json_encode([
        '@context' => 'asx://brain-mesh/install',
        'status' => 'already_installed',
        'message' => 'Brain Mesh is already installed. Add ?force=1 to reinstall.'
    ]);
    exit;
}

// Handle JSON API requests
if ($_SERVER['REQUEST_METHOD'] === 'POST' &&
    strpos($_SERVER['CONTENT_TYPE'] ?? '', 'application/json') !== false) {

    header("Content-Type: application/json");
    $data = json_decode(file_get_contents('php://input'), true);

    if (!$data) {
        http_response_code(400);
        echo json_encode(['error' => 'Invalid JSON']);
        exit;
    }

    $result = runInstallation($data);
    echo json_encode($result);
    exit;
}

// Handle form POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $data = [
        'db_host' => $_POST['db_host'] ?? 'localhost',
        'db_port' => $_POST['db_port'] ?? '3306',
        'db_name' => $_POST['db_name'] ?? '',
        'db_user' => $_POST['db_user'] ?? '',
        'db_pass' => $_POST['db_pass'] ?? '',
        'create_db' => isset($_POST['create_db'])
    ];

    $result = runInstallation($data);
    $installResult = $result;
}

/**
 * Run the installation process
 */
function runInstallation(array $data): array {
    global $configFile, $lockFile;

    $host = $data['db_host'] ?? 'localhost';
    $port = $data['db_port'] ?? '3306';
    $dbName = $data['db_name'] ?? '';
    $user = $data['db_user'] ?? '';
    $pass = $data['db_pass'] ?? '';
    $createDb = $data['create_db'] ?? false;

    // Validate required fields
    if (empty($dbName) || empty($user)) {
        return [
            '@context' => 'asx://brain-mesh/install',
            'success' => false,
            'error' => 'Database name and username are required'
        ];
    }

    try {
        // First connect without database to potentially create it
        if ($createDb) {
            $dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);

            // Create database if not exists
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo = null;
        }

        // Connect to the database
        $dsn = "mysql:host={$host};port={$port};dbname={$dbName};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // Run schema
        $schemaFile = __DIR__ . '/schema.sql';
        if (!file_exists($schemaFile)) {
            return [
                '@context' => 'asx://brain-mesh/install',
                'success' => false,
                'error' => 'schema.sql not found'
            ];
        }

        $schema = file_get_contents($schemaFile);

        // Split into individual statements (handle MySQL multi-statement)
        $statements = array_filter(
            array_map('trim', explode(';', $schema)),
            fn($s) => !empty($s) && !preg_match('/^--/', $s)
        );

        $executed = 0;
        $errors = [];

        foreach ($statements as $stmt) {
            if (empty(trim($stmt))) continue;

            try {
                $pdo->exec($stmt);
                $executed++;
            } catch (PDOException $e) {
                // Ignore duplicate key errors (re-install scenario)
                if (strpos($e->getMessage(), 'Duplicate') === false) {
                    $errors[] = $e->getMessage();
                }
            }
        }

        // Verify tables exist
        $tables = $pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
        $requiredTables = ['brains', 'brain_scores', 'brain_executions', 'cm1_phases', 'error_queue', 'routing_rules'];
        $missingTables = array_diff($requiredTables, $tables);

        if (!empty($missingTables)) {
            return [
                '@context' => 'asx://brain-mesh/install',
                'success' => false,
                'error' => 'Missing tables: ' . implode(', ', $missingTables),
                'tables_found' => $tables
            ];
        }

        // Count brains
        $brainCount = $pdo->query("SELECT COUNT(*) FROM brains")->fetchColumn();

        // Generate config file
        $configContent = <<<PHP
<?php
/**
 * Brain Mesh Configuration
 *
 * Auto-generated by installer
 * @law ASX = XCFE = XJSON = KUHUL = AST = CM-1
 */

return [
    'db' => [
        'host' => '{$host}',
        'port' => '{$port}',
        'name' => '{$dbName}',
        'user' => '{$user}',
        'pass' => '{$pass}',
        'charset' => 'utf8mb4'
    ],

    'adaptive' => [
        'exploration_rate' => 0.1,
        'score_weights' => [
            'success_rate' => 0.5,
            'speed' => 0.3,
            'consistency' => 0.2
        ],
        'promotion_threshold' => 0.85,
        'demotion_threshold' => 0.4,
        'rolling_window_size' => 50,
        'min_executions_for_tier' => 10
    ],

    'cm1' => [
        'enabled' => true,
        'phase_tracking' => true,
        'scope_management' => true
    ],

    'installed_at' => '{$_SERVER['REQUEST_TIME']}'
];
PHP;

        file_put_contents($configFile, $configContent);

        // Create lock file
        file_put_contents($lockFile, date('c'));

        return [
            '@context' => 'asx://brain-mesh/install',
            'success' => true,
            'message' => 'Brain Mesh installed successfully',
            'stats' => [
                'statements_executed' => $executed,
                'tables_created' => count($requiredTables),
                'brains_registered' => (int)$brainCount,
                'errors' => $errors
            ],
            'config_file' => $configFile
        ];

    } catch (PDOException $e) {
        return [
            '@context' => 'asx://brain-mesh/install',
            'success' => false,
            'error' => 'Database error: ' . $e->getMessage()
        ];
    } catch (Exception $e) {
        return [
            '@context' => 'asx://brain-mesh/install',
            'success' => false,
            'error' => $e->getMessage()
        ];
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brain Mesh Installer | CM-1 Micronaut System</title>
    <style>
        :root {
            --emerald-500: #10b981;
            --emerald-600: #059669;
            --emerald-700: #047857;
            --emerald-900: #064e3b;
            --glass-bg: rgba(16, 185, 129, 0.08);
            --glass-border: rgba(16, 185, 129, 0.2);
            --text-primary: #f0fdf4;
            --text-secondary: #a7f3d0;
            --bg-dark: #0a0f0d;
            --bg-card: rgba(6, 78, 59, 0.3);
        }

        * { box-sizing: border-box; margin: 0; padding: 0; }

        body {
            font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace;
            background: var(--bg-dark);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
            background-image:
                radial-gradient(circle at 20% 80%, rgba(16, 185, 129, 0.1) 0%, transparent 50%),
                radial-gradient(circle at 80% 20%, rgba(16, 185, 129, 0.05) 0%, transparent 50%);
        }

        .installer {
            width: 100%;
            max-width: 500px;
            background: var(--bg-card);
            border: 1px solid var(--glass-border);
            border-radius: 16px;
            padding: 2rem;
            backdrop-filter: blur(20px);
        }

        .header {
            text-align: center;
            margin-bottom: 2rem;
        }

        .header h1 {
            font-size: 1.5rem;
            color: var(--emerald-500);
            margin-bottom: 0.5rem;
        }

        .header .glyph {
            font-size: 2rem;
            margin-bottom: 1rem;
            opacity: 0.8;
        }

        .header p {
            color: var(--text-secondary);
            font-size: 0.875rem;
        }

        .form-group {
            margin-bottom: 1.25rem;
        }

        label {
            display: block;
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-secondary);
            margin-bottom: 0.5rem;
        }

        input[type="text"],
        input[type="password"],
        input[type="number"] {
            width: 100%;
            padding: 0.75rem 1rem;
            background: rgba(0, 0, 0, 0.3);
            border: 1px solid var(--glass-border);
            border-radius: 8px;
            color: var(--text-primary);
            font-family: inherit;
            font-size: 0.875rem;
            transition: border-color 0.2s, box-shadow 0.2s;
        }

        input:focus {
            outline: none;
            border-color: var(--emerald-500);
            box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.2);
        }

        input::placeholder {
            color: rgba(167, 243, 208, 0.4);
        }

        .row {
            display: grid;
            grid-template-columns: 2fr 1fr;
            gap: 1rem;
        }

        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            margin-bottom: 1.5rem;
        }

        .checkbox-group input[type="checkbox"] {
            width: 18px;
            height: 18px;
            accent-color: var(--emerald-500);
        }

        .checkbox-group label {
            margin: 0;
            font-size: 0.875rem;
            text-transform: none;
            letter-spacing: normal;
        }

        button {
            width: 100%;
            padding: 1rem;
            background: linear-gradient(135deg, var(--emerald-600), var(--emerald-700));
            border: none;
            border-radius: 8px;
            color: white;
            font-family: inherit;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(16, 185, 129, 0.3);
        }

        button:active {
            transform: translateY(0);
        }

        .result {
            margin-top: 1.5rem;
            padding: 1rem;
            border-radius: 8px;
            font-size: 0.875rem;
        }

        .result.success {
            background: rgba(16, 185, 129, 0.2);
            border: 1px solid var(--emerald-500);
        }

        .result.error {
            background: rgba(239, 68, 68, 0.2);
            border: 1px solid #ef4444;
            color: #fca5a5;
        }

        .result h3 {
            margin-bottom: 0.5rem;
        }

        .result ul {
            list-style: none;
            padding-left: 0;
        }

        .result li {
            padding: 0.25rem 0;
            display: flex;
            justify-content: space-between;
        }

        .result li span:last-child {
            color: var(--emerald-500);
            font-weight: 600;
        }

        .footer {
            margin-top: 2rem;
            text-align: center;
            font-size: 0.75rem;
            color: var(--text-secondary);
            opacity: 0.6;
        }

        .law {
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="installer">
        <div class="header">
            <div class="glyph">⟁ ◰ ◴ ⊟</div>
            <h1>Brain Mesh Installer</h1>
            <p>CM-1 Micronaut System for PHP Broker</p>
        </div>

        <?php if (isset($installResult)): ?>
            <div class="result <?= $installResult['success'] ? 'success' : 'error' ?>">
                <?php if ($installResult['success']): ?>
                    <h3>Installation Complete</h3>
                    <ul>
                        <li><span>Statements executed:</span> <span><?= $installResult['stats']['statements_executed'] ?></span></li>
                        <li><span>Tables created:</span> <span><?= $installResult['stats']['tables_created'] ?></span></li>
                        <li><span>Brains registered:</span> <span><?= $installResult['stats']['brains_registered'] ?></span></li>
                    </ul>
                    <p style="margin-top: 1rem;">Config saved to: <code><?= basename($installResult['config_file']) ?></code></p>
                <?php else: ?>
                    <h3>Installation Failed</h3>
                    <p><?= htmlspecialchars($installResult['error']) ?></p>
                <?php endif; ?>
            </div>
        <?php else: ?>
            <form method="POST">
                <div class="form-group row">
                    <div>
                        <label for="db_host">Database Host</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" placeholder="localhost">
                    </div>
                    <div>
                        <label for="db_port">Port</label>
                        <input type="number" id="db_port" name="db_port" value="3306" placeholder="3306">
                    </div>
                </div>

                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" id="db_name" name="db_name" placeholder="brain_mesh" required>
                </div>

                <div class="form-group">
                    <label for="db_user">Username</label>
                    <input type="text" id="db_user" name="db_user" placeholder="root" required>
                </div>

                <div class="form-group">
                    <label for="db_pass">Password</label>
                    <input type="password" id="db_pass" name="db_pass" placeholder="Enter password">
                </div>

                <div class="checkbox-group">
                    <input type="checkbox" id="create_db" name="create_db" checked>
                    <label for="create_db">Create database if it doesn't exist</label>
                </div>

                <button type="submit">Install Brain Mesh</button>
            </form>
        <?php endif; ?>

        <div class="footer">
            <p class="law">@law ASX = XCFE = XJSON = KUHUL = AST = CM-1</p>
            <p>Brain Mesh v2.0.0</p>
        </div>
    </div>
</body>
</html>
