-- ═══════════════════════════════════════════════════════════════════════════
-- RIG Federation Schema
-- ═══════════════════════════════════════════════════════════════════════════
-- Tables for federated rig management
-- Auto-created by rig-router.php, but can be run manually for setup
--
-- @law ASX = XCFE = XJSON = KUHUL = AST = CM-1
-- @version 2.1.0
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- Rigs Table
-- ─────────────────────────────────────────────────────────────────────────────
-- Stores registered rigs and their capabilities

CREATE TABLE IF NOT EXISTS rigs (
    -- Unique rig identifier (generated by client)
    id VARCHAR(64) PRIMARY KEY,

    -- Human-readable rig name
    name VARCHAR(128) NOT NULL,

    -- JSON array of available model names
    -- Example: ["llama3.2", "mixtral", "codellama"]
    models JSON,

    -- JSON object with rig capabilities
    -- Example: {"platform": "linux", "gpu": "RTX 4090", "vram": "24GB", "arch": "x64"}
    capabilities JSON,

    -- Current status
    status ENUM('online', 'offline', 'busy') DEFAULT 'offline',

    -- Last heartbeat/poll timestamp
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Performance score (0.0 - 1.0)
    -- Updated via epsilon-greedy bandit algorithm
    score DECIMAL(5,3) DEFAULT 0.500,

    -- Request statistics
    total_requests INT DEFAULT 0,
    successful_requests INT DEFAULT 0,
    avg_latency_ms INT DEFAULT 0,

    -- Registration timestamp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Indexes for common queries
    INDEX idx_status (status),
    INDEX idx_score (score DESC),
    INDEX idx_last_seen (last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Rig Requests Table
-- ─────────────────────────────────────────────────────────────────────────────
-- Queue for inference requests to rigs

CREATE TABLE IF NOT EXISTS rig_requests (
    -- Auto-increment request ID
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    -- Target rig
    rig_id VARCHAR(64) NOT NULL,

    -- Client session ID (for routing responses)
    session_id VARCHAR(64),

    -- Model to use for inference
    model VARCHAR(128) NOT NULL,

    -- Input prompt
    prompt TEXT NOT NULL,

    -- JSON options for inference
    -- Example: {"temperature": 0.7, "max_tokens": 1000}
    options JSON,

    -- Response text (filled after completion)
    response TEXT,

    -- Request status
    status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',

    -- Response latency in milliseconds
    latency_ms INT,

    -- Error message if failed
    error_message TEXT,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,

    -- Indexes
    INDEX idx_rig_status (rig_id, status),
    INDEX idx_created (created_at),
    INDEX idx_session (session_id),

    -- Foreign key to rigs table
    FOREIGN KEY (rig_id) REFERENCES rigs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Rig Events Table (Optional - for analytics)
-- ─────────────────────────────────────────────────────────────────────────────
-- Tracks rig lifecycle events for debugging and analytics

CREATE TABLE IF NOT EXISTS rig_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rig_id VARCHAR(64),
    event_type ENUM('register', 'unregister', 'advertise', 'online', 'offline', 'error') NOT NULL,
    details JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_rig_events (rig_id, event_type),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Cleanup Jobs
-- ─────────────────────────────────────────────────────────────────────────────

-- Mark stale rigs as offline (run periodically)
-- UPDATE rigs SET status = 'offline'
-- WHERE status = 'online' AND last_seen < DATE_SUB(NOW(), INTERVAL 2 MINUTE);

-- Clean up old completed requests (run daily)
-- DELETE FROM rig_requests
-- WHERE status IN ('completed', 'failed') AND created_at < DATE_SUB(NOW(), INTERVAL 7 DAY);

-- Clean up old events (run weekly)
-- DELETE FROM rig_events
-- WHERE created_at < DATE_SUB(NOW(), INTERVAL 30 DAY);
